---
title: "HW4"
date: "2/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls()); gc();
setwd("c:/Users/Jerry/Desktop/GBA424/Wine Retailer Case")
library(dplyr)
library(tidyr)
library(data.table)
library(ggplot2)
library(grf)

df = read.csv("test_data_1904.csv")
```

```{r }
dt = data.table(df)
dagg = dt[,.(open = mean(open), click=mean(click), purch = mean(purch),seOpen = sd(open)/sqrt(.N), seClick=sd(click)/sqrt(.N), sePurch = sd(purch)/sqrt(.N),.N),by = .(group)]
dagg
```

```{r}
dodge = position_dodge(width=1); ##to form constant dimensions
ggplot(aes(x=group,y=purch,ymax=purch+sePurch,ymin=purch-sePurch),data=dagg)+
  geom_bar(position=dodge,stat="identity",col=2:3,fill=2:3) + 
  geom_errorbar(position=dodge)
  labs(x="Group",y="Purchases")
```
```{r Question A}
summary(lm(purch~group,data=df))
```
The effect size is $1.35 for email. 

```{r}
summary(lm(purch~group+chard+sav_blanc+syrah+cab+last_purch+visits,data=df))
```

```{r}
hist(df$last_purch, 
     xlab="Days Since Last Purchase", ylab="Customers", 
     main="Histogram of Days Since Last Purchase")
df$recentPurch = (df$last_purch < 60)
dt = data.table(df)
```

```{r Slicing and Dicing: recent buyers versus aged customers}
dagg = dt[,.(open = mean(open), click=mean(click), purch = mean(purch),seOpen = sd(open)/sqrt(.N), seClick=sd(click)/sqrt(.N), sePurch = sd(purch)/sqrt(.N),.N),by = .(group,recentPurch)]
dagg
```
-Recent purchesed customers do buy more than not
-The email seems to produce a stronger effect on purchases for more recent buyers

```{r, echo=FALSE, warning=FALSE}
dodge = position_dodge(width=1); ##to form constant dimensions
ggplot(aes(fill=group,y=purch,x=recentPurch,ymax=purch+sePurch,ymin=purch-sePurch),data=dagg)+
  geom_bar(position=dodge,stat="identity") + 
  geom_errorbar(position=dodge)
  labs(x="Group",y="Purchases")
``` 

```{r Slicing and Dicing: syrah}
df$syrahOrNot = (df$syrah !=0)
dt = data.table(df)
dagg = dt[,.(open = mean(open), click=mean(click), purch = mean(purch),seOpen = sd(open)/sqrt(.N), seClick=sd(click)/sqrt(.N), sePurch = sd(purch)/sqrt(.N),.N),by = .(group,syrahOrNot)]
dagg
```

